apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: next-js
  name: nextjs-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: standard
  hostPath:
    path: /var/lib/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: next-js
  name: nextjs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: nextjs-pv